### ISSUE TITLE
delete_virtual_server doesn't delete

### ISSUE THREAD

**Issue by eheydrick** [magec/icontrol#1]
IControl::LocalLB::VirtualServer.delete_virtual_server is sending the wrong SOAP parameters and not actually deleting the VS. http://devcentral.f5.com/wiki/default.aspx/iControl/LocalLB__VirtualServer__delete_virtual_server.html says that the virtual_servers parameter should be a string of virtual server names. icontrol is sending the id of the virtual server and the F5 responds with unknown virtual server.

**Comment by magec** [comment]
The current code at master is quite experimental still, though it will be actual release. If you want to have the things you comment working you better go back in time to the tag v0.1 (commit d1879b89eb38562a1e22fc03efbfbcd2a04a6215). Either way, given that this issue currently applies, I will keep it. If you have any ideas or comments or whatever question don't hesitate to ask.

**Comment by magec** [comment]
As of release 0.3.5 this is solved
